### ISSUE TITLE
Exception if a host sends different handshake message

### ISSUE THREAD

**Issue by geext-dk** [alexforster/AmiClient#4]
Hi.
I noticed that your code throws an exception if the first message server sends to you doesn't start with "Asterisk Call Manager". Is it really necessary to do this check? I'm trying to work with a kind of emulator of AMI but it's sending different first message, hence I can't make your library work with it.

**Comment by alexforster** [comment]
Interesting. It's certainly not necessary, but I do like having some sort of sanity check that says "I'm connected to something that looks like an Asterisk server".

Does this emulator emit one line followed by \r\n?

**Comment by geext-dk** [comment]
Yes. Without the part that throws the exception your library works flawlessly. The library still reads the first line, but instead just ignores it.
I think it's responsibility of a developer, not library, to connect to the correct server. If the library connects to the wrong server, it won't work anyway. If it connects to the server that tries to mimic AMI for bad purposes, it isn't hard for the server to send correct handshake message, so there isn't much point as far as I know.

**Comment by alexforster** [comment]
Yeah this isn't a problem. I need to check that the server emits _something_ so that [this check keeps working](https://github.com/alexforster/AmiClient/blob/master/AmiClient.cs#L70), but I don't think it's necessary to check for the correct verbiage. I'll just check that I successfully read a non-empty line. I'll cut a new release tonight or tomorrow.

**Comment by geext-dk** [comment]
Thank you very much.
