### ISSUE TITLE
Ergonomics of handling server failure

### ISSUE THREAD

**Issue by geext-dk** [alexforster/AmiClient#8]
If the server the AmiClient is connected to closes the connection there is no way to find it out.
WorkerMain is throwing an exception, and it can't be caught because it is in a separate task.

Currently in case of closing the connection lineObserver.TakeUntil throws with an InvalidOperationException with a message "The sequence contains no elements").

**Comment by alexforster** [comment]
If the worker thread throws an exception of any kind, [it's dispatched to all subscribed `IObserver`s](https://github.com/alexforster/AmiClient/blob/7c85097998ba0db32a703c802536ff410a59abde/AmiClient.cs#L216).

Example...

```csharp
internal static class Program
{
  static void OnException(Exception ex)
  {
    Console.Error.WriteLine("Exception: {0}", ex);
    Environment.Exit(1);
  }

  public static async Task Main(String[] args)
  {
    using(var socket = new TcpClient(hostname: "127.0.0.1", port: 5038))
    using(var client = new AmiClient(socket.GetStream()))
    using(client.Subscribe(_ => {}, Program.OnException))
    {
      ...
      ...
    }
  }
}
```

However, I will say the ergonomics around this aren't entirely fleshed out. I'm open to suggestions here – one thing I don't currently like is that [the `Publish` method just returns null rather than re-throwing an exception](https://github.com/alexforster/AmiClient/blob/7c85097998ba0db32a703c802536ff410a59abde/AmiClient.cs#L129) when trying to write to a broken socket. Originally I didn't want users to have to do heavy exception handling, but I'm not sure that was the right choice.
